### PR TITLE
Add aid to navigation encoding

### PR DESCRIPTION
**Pull request by sbender9**

### CODE REVIEW

**Comment by fulup-bzh** [comment]
Thank you for your contribution

**Comment by sbender9** [comment]
You're welcome. Can you please publish a release to npm also?

**Comment by sbender9** [comment]
Actually, hold off on the npm, I think I found an issue

**Comment by sbender9** [comment]
OK, issue was on my side. Please publish when you have time. Thanks!

**Comment by fulup-bzh** [comment]
NPM published

**Pull request merged**
