### PR TITLE
Added Rate of turn and special maneuvre indicator

### PR DESCRIPTION
**Pull request by stockulus**
Hi! 

Thanks for the cool lib. The AIS Parser helps me a lot. 

I just added 2 Fields from the AIS Message:
- Rate of Turn
- special maneuvre indicator
https://www.navcen.uscg.gov/?pageName=AISMessagesA

Greez Christoph

### CODE REVIEW

**Comment by fulup-bzh** [comment]
Thank you for your contribution

**Comment by stockulus** [comment]
Hi, 

is it possible that you push the new Version to npm?

Greez Christoph

**Comment by fulup-bzh** [comment]
Done

**Comment by stockulus** [comment]
Thanks!!

**Pull request merged**
