### PR TITLE
repair on test script for msg 9,14,19

### PR DESCRIPTION
**Pull request by afischerdev**
Repair is ready  and no conflicts this time.
I changed the package.json again.

### CODE REVIEW

**Comment by afischerdev** [comment]
Again, but this time a package - version is already 0.1.15, I commited 0.1.14
Is there an automatic update?

**Comment by afischerdev** [comment]
Hi, I'm sorry to disturb you, could you please also merge into fulup-bzh:master? 
The not working version 0.1.15 is public and comes out on npm install.

**Comment by fulup-bzh** [comment]
Done I publish your commit on NPM

**Comment by afischerdev** [comment]
Great, thanks, now working as expected.

**Pull request merged**
