### PR TITLE
Add ais msg 9,14,19

### PR DESCRIPTION
**Pull request by afischerdev**
Added ais msg 9,14,19 and did some smaller changes in older messages.

### CODE REVIEW

**Comment by afischerdev** [comment]
I'm sorry for the conflicts. But I don't understand why this are conflicts. I made changes and that's it.

**Comment by fulup-bzh** [comment]
I cannot merge your commit as they is conflict that should be resevolved first. You propose
`this.sog = parseFloat (0.1 * this.GetInt(  50, 10 )); ` when the original code was `this.sog = this.GetInt(  50, 10) / 10;'.  In current context parseFloat() does not make value, as the value is already a float and adding a string conversion is not usefull.

You also introduce a small conflict in EncodingDecodeTest

**Comment by fulup-bzh** [comment]
On 23/02/2017 12:10, afischerdev wrote:
    
    
      I'm sorry for the conflicts. But I don't understand why this
        are conflicts. I made changes and that's it.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fulup-bzh/GeoGate","title":"fulup-bzh/GeoGate","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fulup-bzh/GeoGate"}},"updates":{"snippets":[{"icon":"PERSON","message":"@afischerdev in #18: I'm sorry for the conflicts. But I don't understand why this are conflicts. I made changes and that's it."}],"action":{"name":"View Pull Request","url":"https://github.com/fulup-bzh/GeoGate/pull/18#issuecomment-281964279"}}}
    
    No an issue, it just append that your change proposal are in
    conflict with git, and that until they are solved they is no way to
    merge your work.
    
    
    -- 
      
          Fulup Ar Foll, CEO
          Tel: +33.257.620.241 Mobile: +33.619.921.323
           www.iot.bzh

**Comment by afischerdev** [comment]
Thanks for the comment. but in my opinion it was the other way round
it was                  = this.sog = parseFloat (0.1 * this.GetInt( 50, 10 ));
and I changed to = this.sog = this.GetInt( 50, 10) / 10;

**Comment by fulup-bzh** [comment]
kool, but in this case I do not understand why they is a conflict. What might be possible, it that your repo was not sync before you made the modification. I'm not an expert of git. But you might want to update your repo before applying your patches. This might be the reason for the conflict.

**Comment by afischerdev** [comment]
Yes, I did a refresh before I started, 
Anyway, what do you think? Close this and restart a new one with changed files?

**Comment by fulup-bzh** [comment]
Ok I merge your pull request, by hand. 

But I could have done mistakes. I would be please you to syncup your repo with Master and check the outcome. I'm especially surprise by your change on encoder/test/AisEncodeDecodeTest.js where your test replace an existing one, when you should have add a new test without removing the old one.

When you will be done, let me know, I will push a new npm version.

**Comment by afischerdev** [comment]
Ok, I see the changes. And I found two missing samples in AisEncodeDecodeTest.js. 
And also there is a missing break. Script will not work at the moment. 
I will correct that and start a new pull request.

**Comment by fulup-bzh** [comment]
No problem, let's me know when your done and will push a new release to update both npm and bower

**Comment by fulup-bzh** [comment]
Question are we done after this new push ? Or do you sill want to change something else before I update npm+bower ?

**Comment by afischerdev** [comment]
No changes, only repair on test script and cosmetic - I have seen my editor still produces tabs and not blanks.
the package.json was also changed.

**Comment by fulup-bzh** [comment]
Cool, I add to change package.log again as master version was late compare to NPM. Look like we're now back a stable situation.
Thank you

**Pull request merged**
